INSERT INTO `CSS` (`id`, `course_id`, `title`, `desc`, `img_count`, `has_coding`) VALUES (1, 13, 'CSS의 도입', ' <div class="smalltitle"> CSS (Cascading Style Sheets) </div><br /> CSS를 사용하면 지금까지 HTML을 이용해서 만들었던 페이지의 요소들을 화려하게 꾸밀 수 있습니다.<br /> 예컨대 글자의 폰트를 바꾸고, 배경색을 주고, 정렬 방법을 다르게 하고..<br /> 이 강좌에선 CSS를 이용해서 웹페이지의 디자인을 제어하는 방법을 알아봅니다.<br /><br /> 자, 그럼 시작해 볼까요?', 1, 'false');
INSERT INTO `CSS` (`id`, `course_id`, `title`, `desc`, `img_count`, `has_coding`) VALUES (2, 14, 'CSS 규칙', 'CSS는 <b>선택자(selector)</b>와 <b>선언(declaration)</b>으로 이루어져 있습니다.<br /><br /> 중괄호 앞의 선택자는 <span class="underlinedtext">어떤 요소에 규칙을 적용할지 결정합니다.</span><br /> 중괄호 안의 선언은 <span class="underlinedtext">선택자로 지정한 요소에 어떤 스타일을 줄지 결정합니다.</span><br /><br /> 선언 안에서는 ‘(속성) : (값);‘의 형식으로 스타일을 지정할 수 있습니다.<br /> 예를 들어 <code>&lt;p&gt;</code>태그 안의 모든 내용의 색상을 빨간색으로 주고 싶다면,<br /> &nbsp;&nbsp;p { color : yellow; } 라고 쓸 수 있습니다.<br /><br /> 항상 속성-값 뒤에 세미콜론이 온다는 사실에 주의합시다.', 1, 'true');
INSERT INTO `CSS_Coding` (`course_id`, `instruction`) VALUES (14, '<code>body</code> 태그 안에 있는 요소들의 색상을 검은색으로 지정하는 CSS 코드를 추가해 보세요.');
INSERT INTO `CSS` (`id`, `course_id`, `title`, `desc`, `img_count`, `has_coding`) VALUES (3, 15, 'CSS의 다양한 선택자', '앞에서 살펴본 가장 간단한 선택자 외에도 CSS에서는 다양한 선택자들을 지원합니다.<br /><br /> 다음은 그 중 자주 사용되는 몇 가지입니다.', 1, 'true');
INSERT INTO `CSS_Coding` (`course_id`, `instruction`) VALUES (15, '<code>class</code> 속성의 값이 container인 요소를 대상으로<br /> 색상을 빨간색으로 지정하는 CSS 코드를 작성해 보세요.');
INSERT INTO `CSS` (`id`, `course_id`, `title`, `desc`, `img_count`, `has_coding`) VALUES (4, 16, 'HTML 내부에 CSS 코드 작성하기', 'CSS 코드를 열심히 작성했는데 그걸 HTML 코드에 연결하는 방법을 모른다면 무용지물이겠죠.<br /><br /> <code>&lt;head&gt;</code> 태그 안에 <code>&lt;style&gt;</code>태그를 넣어서 CSS를 포함시킬 수 있습니다.<br /> <code>&lt;style&gt;</code>태그는 type 속성을 통해서 ‘이 스타일은 CSS로 지정되었다’를 나타냅니다.<br />', 1, 'true');
INSERT INTO `CSS_Coding` (`course_id`, `instruction`) VALUES (16, 'HTML 코드 내부에 CSS 코드를 작성하고, 적용시켜 보세요.');
INSERT INTO `CSS` (`id`, `course_id`, `title`, `desc`, `img_count`, `has_coding`) VALUES (5, 17, 'HTML에서 외부 CSS 코드 불러오기', '<div class="smalltitle">CSS 파일을 외부로 분리함으로써 얻을 수 있는 이점은 다음과 같습니다.</div><br /> 1. 한 CSS 문서를 여러 HTML 문서가 포함시킬 수 있습니다.<br /> 2. 컨텐츠와 디자인을 분리할 수 있습니다.<br /> 3. 코드 재사용이 용이해집니다.<br /><br /> 외부의 CSS 코드를 HTML 코드에 링크시키기 위해서는 <code>&lt;link&gt;</code>태그를 이용합니다.<br /> <code>&lt;link&gt;</code> 태그 안에는 세 가지 속성이 있습니다.<br /><br /> <code>href</code> : 링크할 CSS 문서의 경로를 가리킵니다.<br /> <code>type</code> : 연결할 문서의 타입을 지정합니다. ‘text/css’ 값이 위치합니다.<br /> <code>rel</code> : 연결할 문서와의 관계를 지정합니다. CSS 문서와 연결할 때는 ‘stylesheet’ 값을 가집니다.', 1, 'true');
INSERT INTO `CSS_Coding` (`course_id`, `instruction`) VALUES (17, 'HTML 파일에 외부 CSS 파일을 링크시키고, CSS 코드를 자유롭게 작성해 보세요.<br /> CSS 파일의 이름은 stylesheet.css입니다.');
INSERT INTO `CSS` (`id`, `course_id`, `title`, `desc`, `img_count`, `has_coding`) VALUES (6, 18, '다양한 색상 지정하기', '<div class="smalltitle"> 전경색 – color </div> <b>color</b> 프로퍼티로 전경색을 지정할 수 있습니다.<br /> 색을 지정하는 방법은 대표적으로 세 가지가 있습니다.<br /><br /> 1. RGB 값으로 지정하기<br /> <code>color : rgb(218, 247, 184);</code><br /> 2. 16진수 색상 코드로 지정하기<br /> <code>color : #FF9330;</code><br /> 3. 색 이름으로 지정하기<br /> <code>color : skyblue;</code><br /><br /> <div class="smalltitle"> 배경색 – background-color </div><br /> <code>background-color</code> 프로퍼티로 배경색을 지정할 수 있습니다.', 1, 'true');
INSERT INTO `CSS_Coding` (`course_id`, `instruction`) VALUES (18, '세 가지 방법을 이용해서 색상을 지정해 보세요.');
INSERT INTO `CSS` (`id`, `course_id`, `title`, `desc`, `img_count`, `has_coding`) VALUES (7, 19, '텍스트 제어 – 폰트 지정하기', '<div class="smalltitle"> font-family </div> 텍스트의 폰트를 지정하기 위해선 <code>font-family</code> 프로퍼티를 사용합니다.<br /> 폰트는 한번에 여러 개를 지정하는 게 일반적입니다. 첫 번째로 지정한 폰트가 사용자의 컴퓨터에 없을 경우를 대비해서입니다.<br /> 만약 첫 번째로 지정된 폰트가 사용자의 컴퓨터에 설치되어 있지 않다면, 웹브라우저는 그 다음으로 지정된 폰트를 표시합니다.<br /><br /> 대부분 원하는 폰트 뒤에, 범용적인 폰트를 지정합니다.<br /><br /> 폰트명이 여러 단어인 경우에는 큰따옴표로 묶어서 지정합니다.', 1, 'true');
INSERT INTO `CSS_Coding` (`course_id`, `instruction`) VALUES (19, '<code>&lt;h1&gt;</code> 요소와 <code>&lt;p&gt;</code> 요소의 폰트를 바꿔 보세요.');
INSERT INTO `CSS` (`id`, `course_id`, `title`, `desc`, `img_count`, `has_coding`) VALUES (8, 20, '텍스트 제어 – 폰트의 크기', '<div class="smalltitle"> font-size </div> font-size 프로퍼티로 폰트의 크기를 조절할 수 있습니다.<br /> 크기는 픽셀, 퍼센트, em 등의 단위로 조절할 수 있습니다.<br /><br /> <span class="underlined">픽셀은 해상도에 영향을 받습니다.</span> 1920×1080 해상도일 때보다 800×600일 때 더 크게 보입니다.<br /><br /> <span class="underlined">퍼센트는 브라우저에서 텍스트의 기본 크기에 영향을 받습니다.</span><br /> 일반적으로 브라우저에서 텍스트의 기본 크기는 16px입니다.<br /> 따라서 50%는 8px이고, 200%는 32px입니다.<br /><br /> <span class="underlined"><code>em</code>은 현재 글자의 크기를 의미합니다.</span><br /> 예를 들어 A요소의 부모 요소 글자 크기가 30px이라면 A요소의 글자 크기는 부모 요소로부터 상속받아 30px이 됩니다.<br /> 그 상태에서 A요소의 글자 크기를 0.9em으로 지정한다면 27px이 되는 것이죠! (30×0.9=27)', 1, 'true');
INSERT INTO `CSS_Coding` (`course_id`, `instruction`) VALUES (20, '주어진 <code>&lt;h1&gt;</code>요소와 <code>&lt;p&gt;</code>요소의 폰트 크기를 바꿔 보세요.');
INSERT INTO `CSS` (`id`, `course_id`, `title`, `desc`, `img_count`, `has_coding`) VALUES (9, 21, '텍스트 제어 – 폰트의 스타일', '<div class="smalltitle"> font-weight </div> <code>font-weight</code> 프로퍼티를 사용해서 텍스트를 굵게 나타낼 수 있습니다.<br /> <code>font-weight</code> 프로퍼티에는 다음 두 가지 값을 할당할 수 있습니다.<br /><br /> <code class="code_value">normal</code> : 텍스트를 일반 스타일로 나타냅니다.<br /> <code class="code_value">bold</code> : 텍스트를 굵게 나타냅니다.<br /><br /> <code class="code_value">normal</code>이 필요할까? 라는 의문을 가진다면, <code>&lt;div&gt;</code>태그 안에 <code>&lt;p&gt;</code>태그가 있다고 생각해보세요.<br /> <code>&lt;div&gt;</code> 안의 모든 폰트를 굵게 하고, <code>&lt;p&gt;</code> 요소만 굵게 하지 않고 싶을 때 <code class="value">normal</code> 값을 적용합니다.<br /><br /> <div class="smalltitle"> font-style </div> <code>font-style</code> 프로퍼티를 사용하면 텍스트를 기울일 수 있습니다.<br /> <code>font-style</code> 프로퍼티에는 다음 값들을 할당할 수 있습니다.<br /><br /> <code class="value">normal</code> : 텍스트를 일반 스타일로 나타냅니다.<br /> <code class="value">italic</code> : 텍스트를 이탤릭체로 나타냅니다.<br /> <code class="value">oblique</code> : 텍스트를 기울여서 나타냅니다.<br /><br /> italic체와 oblique체는 둘 다 기울임꼴이지만, 다른 폰트입니다.<br /> italic체는 폰트 디자이너가 따로 만들어 둔 기울임 폰트입니다.<br /> 반면 oblique체는 단순히 일반 폰트를 기울여서 만든 폰트입니다.<br /><br /> 웹브라우저가 italic체를 찾지 못한다면 일반 폰트에 기울이는 알고리즘을 적용해서 만듭니다.', 1, 'true');
INSERT INTO `CSS_Coding` (`course_id`, `instruction`) VALUES (21, '주어진 단락에 <code>&lt;span&gt;</code>태그를 사용해서 중요한 단어를 묶은 뒤, 굵게 표시하거나 기울여서 표시해 보세요.');


/*
INSERT INTO `CSS` (`id`, `course_id`, `title`, `desc`, `img_count`, `has_coding`) VALUES (장 번호, 장 번호, '제목', '내용', 이미지개수, '코딩지시여부');
INSERT INTO `CSS_Coding` (`course_id`, `instruction`) VALUES (장 번호, '지시사항');
*/
